### ISSUE TITLE
possible typo in soft-theme.css line1

### ISSUE THREAD

**Issue by gnanet** [iYUYUE/transmission-web-theme#1]
This looks like a typo to me, in case you see some issues

https://github.com/iYUYUE/transmission-web-theme/blob/17df6b4c6805977e14d9a7461904e5b79b70d025/style/transmission/soft-theme.css#L1

```css
9html {
  cursor: default;
}
```
